# Generated by Django 2.0.1 on 2018-02-10 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='NivelAcceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=74)),
            ],
            options={
                'db_table': 'nomenclador_nivel_acceso',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=32)),
                ('apellidos', models.CharField(max_length=32)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclador.Departamento')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UnidadOrganizativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('acronimo', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'nomenclador_unidad_organizativa',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='trabajador',
            name='unidad_organizativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclador.UnidadOrganizativa'),
        ),
    ]
