# Generated by Django 2.0.1 on 2018-02-10 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=108)),
                ('extension', models.CharField(max_length=7)),
                ('size', models.FloatField()),
                ('path', models.CharField(max_length=140)),
                ('descripcion', models.CharField(max_length=120, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('descripcion', models.CharField(max_length=120, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Ejecutante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observacion', models.CharField(max_length=102, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('ultima_entrada', models.DateTimeField(null=True)),
                ('requiere_adjunto', models.BooleanField(default=False)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EjecutanteAccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=256)),
                ('pronostico', models.DateField(null=True)),
                ('ejecutante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarea_operativa.Ejecutante')),
            ],
            options={
                'db_table': 'tarea_operativa_ejecutante_accion',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PeriodoChequeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=24)),
                ('dia_semana', models.CharField(max_length=20, null=True)),
                ('fecha_especifica', models.CharField(max_length=153, null=True)),
            ],
            options={
                'db_table': 'tarea_operativa_periodo_chequeo',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Prorroga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('fecha_ended_to', models.DateField()),
                ('prorroga', models.DateField()),
                ('motivo', models.CharField(max_length=120)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TareaOperativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('numero', models.IntegerField()),
                ('fecha_start', models.DateField()),
                ('fecha_ended', models.DateField()),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=False)),
                ('publica', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarea_operativa.Categoria')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tarea_operativa',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='prorroga',
            name='tarea_operativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarea_operativa.TareaOperativa'),
        ),
        migrations.AddField(
            model_name='periodochequeo',
            name='tarea_operativa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tarea_operativa.TareaOperativa'),
        ),
        migrations.AddField(
            model_name='ejecutante',
            name='tarea_operativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarea_operativa.TareaOperativa'),
        ),
        migrations.AddField(
            model_name='ejecutante',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='ejecutante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tarea_operativa.Ejecutante'),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='tarea_operativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tarea_operativa.TareaOperativa'),
        ),
        migrations.AlterUniqueTogether(
            name='ejecutante',
            unique_together={('user', 'tarea_operativa')},
        ),
    ]
